a=open("student.txt","w")
print("Enter the student name: ")
name=input()
print("Enter the student enrollment number: ")
eno=int(input())
print("Enter the department")
dept=input()
a.write("Name: "+name)
a.write("\nEnrollment no:"+str(eno))
a.write("\nDepartment:"+dept)
a.close()
a=open("student.txt","r")
print(a.read())
